version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run typescript checker
          command: npx tsc --noEmit
      - run:
          name: Package lock security test
          command: npx lockfile-lint --path package-lock.json --allowed-hosts npm yarn
      - run:
          name: Build application
          command: npm run build
      - run:
          name: Run tests
          command: npm run test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
